#!/bin/bash
# Generated by f5-cert-push. Restores the BIG-IP state captured just before run 20260930-162806.
# Run on the BIG-IP as root:   bash restore-20260930-162806.sh
set -u
D="$(cd "$(dirname "$0")" && pwd)"
if [ -s "$D/SHA256SUMS" ]; then
  ( cd "$D" && sha256sum -c --quiet SHA256SUMS ) || { echo "backup integrity check FAILED; nothing was changed" >&2; exit 1; }
fi
failed() { printf '%s\n' "$1" | grep -Eq '^[0-9a-fA-F]{8}:[0-3]:|transaction failed|Syntax Error|Unexpected Error'; }
inst() {
  out="$(tmsh install sys crypto "$1" "$2" from-local-file "$3" 2>&1)"
  if failed "$out"; then echo "install of $1 $2 FAILED: $out" >&2; exit 1; fi
  echo "    reinstalled $1 $2"
}
exists() { [ -n "$(tmsh -q list sys file "$1" "$2" 2>/dev/null)" ]; }
ensure() {
  if [ "$1" = key ]; then c=ssl-key; else c=ssl-cert; fi
  if exists "$c" "$2"; then echo "    $1 $2 still present"; else inst "$1" "$2" "$3"; fi
}
force() { inst "$1" "$2" "$3"; }
ensure key 'site-privkey-20260901-120000.pem' "$D/key.site-privkey-20260901-120000.pem"
ensure cert 'site-cert-20260901-120000.pem' "$D/cert.site-cert-20260901-120000.pem"
ensure cert 'site-chain-20260901-120000.pem' "$D/cert.site-chain-20260901-120000.pem"
OUT="$({
echo "create cli transaction"
echo 'modify ltm profile client-ssl site-clientssl cert-key-chain modify { site-clientssl { cert site-cert-20260901-120000.pem chain site-chain-20260901-120000.pem key site-privkey-20260901-120000.pem } }'
echo 'modify ltm profile client-ssl www-clientssl cert-key-chain modify { e1 { cert site-cert-20260901-120000.pem chain site-chain-20260901-120000.pem key site-privkey-20260901-120000.pem } }'
echo "submit cli transaction"
} | tmsh 2>&1)"
printf "%s\n" "$OUT"
if failed "$OUT"; then echo "restoring the profiles FAILED" >&2; exit 1; fi
echo "    profiles repointed"
tmsh save sys config > /dev/null
echo '[+] restored the state captured before run 20260930-162806'
